"""partype

Revision ID: 59e80cb91ec
Revises: None
Create Date: 2014-03-06 07:13:21.787215

"""

# revision identifiers, used by Alembic.
revision = '59e80cb91ec'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'case', sa.Column('partype_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'case', 'partype_id')
    op.drop_table('partype')
    ### end Alembic commands ###
