"""case chunklist relationship

Revision ID: a3609c781ec
Revises: 3d1a641806c6
Create Date: 2014-03-09 13:23:51.571229

"""

# revision identifiers, used by Alembic.
revision = 'a3609c781ec'
down_revision = '3d1a641806c6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case', sa.Column('chunklist_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case', 'chunklist_id')
    ### end Alembic commands ###
